name = "relengo-landing-page"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "unsafe_eval"]
main = ".open-next/worker.js"

[observability]
enabled = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
